defaults:
  - dataset: constantcount_h3m
  - augmentation: no_aug
  - training: margipose
 
gpus: 
root_dir: /home/gianlucascarpellini/dev
model_zoo: /longtermdatasets/asude/lifting_events_to_3d_hpe/model_zoo/h36m
load_path: /longtermdatasets/asude/lifting_events_to_3d_hpe/model_zoo/h36m
result_file: aucs.json 
num_workers: 12

batch_size: 256
